name: Library Compile
on: push
jobs:
  build:
    name: Test compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-boards-fqbn:
          - arduino:avr:uno                          # arudino uno
          - arduino:sam:arduino_due_x                # arduino due
          - arduino:samd:nano_33_iot                 # samd21
          - adafruit:samd:adafruit_metro_m4          # samd51
          - esp32:esp32:esp32doit-devkit-v1          # esm32
          - STM32:stm32:GenF1:pnum=BLUEPILL_F103C8   # stm32 bluepill
          - STM32:stm32:Nucleo_64:pnum=NUCLEO_F411RE # stm32 nucleo
          - arduino:mbed_rp2040:pico                 # rpi pico          
        include:
          - arduino-boards-fqbn: arduino:avr:uno
            sketch-names: '**.ino'
            required-libraries: PciManager, Simple FOC
          - arduino-boards-fqbn: arduino:sam:arduino_due_x
            required-libraries: Simple FOC
            sketch-names: '**.ino'            
          - arduino-boards-fqbn: arduino:samd:nano_33_iot
            required-libraries: Simple FOC
            sketch-names: '**.ino'            
          - arduino-boards-fqbn: arduino:mbed_rp2040:pico
            required-libraries: Simple FOC
            sketch-names: '**.ino'            
          - arduino-boards-fqbn: adafruit:samd:adafruit_metro_m4
            platform-url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
            required-libraries: Simple FOC
            sketch-names: '**.ino'          
          - arduino-boards-fqbn: esp32:esp32:esp32doit-devkit-v1
            platform-url: https://dl.espressif.com/dl/package_esp32_index.json
            required-libraries: Simple FOC
            sketch-names: '**.ino'
          - arduino-boards-fqbn: STM32:stm32:GenF1:pnum=BLUEPILL_F103C8
            platform-url: https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json 
            required-libraries: Simple FOC
            sketch-names: '**.ino'            
          - arduino-boards-fqbn: STM32:stm32:Nucleo_64:pnum=NUCLEO_F411RE
            platform-url: https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json 
            required-libraries: Simple FOC
            sketch-names: '**.ino'
      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@master
      with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          required-libraries: ${{ matrix.required-libraries }}
          platform-url: ${{ matrix.platform-url }}
          sketch-names: ${{ matrix.sketch-names }}
          sketches-exclude: ${{ matrix.sketches-exclude }}
